create-links:
	ln -s ${PWD}/agents/* ${HOME}/.config/opencode/agents/.
	ln -s ${PWD}/skills/* ${HOME}/.config/opencode/skills/.
	ln -s ${PWD}/tools/*  ${HOME}/.config/opencode/tools/.

remove-links:
	rm -rf ${HOME}/.config/opencode/agents/codescribe
	rm -rf ${HOME}/.config/opencode/skills/codescribe_*
	rm ${HOME}/.config/opencode/tools/codescribe_*.ts
