# Prompt engineering for building diffusion stencils for constant and variable coefficient equation

# Import libraries
import re
import os, sys, toml, importlib, json, requests

from typing import Optional, List, Dict
from alive_progress import alive_bar

from code_scribe import lib


class LlamaModel:
    def __init__(self, model):

        llama = importlib.import_module("llama")

        self.pipeline = llama.Llama.build(
            ckpt_dir=model,
            tokenizer_path=os.path.join(model, "tokenizer.model"),
            max_seq_len=4096,
            max_batch_size=8,
        )

        self.max_gen_len = None
        self.temperature = 0.5
        self.top_p = 0.95

    def chat(self, chat_template):
        results = self.pipeline.chat_completion(
            [chat_template],
            max_gen_len=self.max_gen_len,
            temperature=self.temperature,
            top_p=self.top_p,
        )
        print(results)
        return results[0]["generation"]["content"]


class OpenAIModel:
    def __init__(self):
        openai = importlib.import_module("openai")
        self.pipeline = openai.OpenAI()
        self.outputs = 1
        self.max_tokens = 4096

    def chat(self, chat_template):
        # We use the Chat Completion endpoint for chat like inputs
        response = self.pipeline.chat.completions.create(
            # model used here is ChatGPT
            # You can use all these models for this endpoint:
            # gpt-4, gpt-4-0314, gpt-4-32k, gpt-4-32k-0314,
            # gpt-3.5-turbo, gpt-3.5-turbo-0301
            # model="gpt-3.5-turbo",
            model="gpt-4o",
            messages=chat_template,
            # max_tokens generated by the AI model
            # maximu value can be 4096 tokens for "gpt-3.5-turbo"
            max_tokens=self.max_tokens,
            # number of output variations to be generated by AI model
            n=self.outputs,
        )

        return response.choices[0].message.content


class ArgoModel:
    def __init__(self, model):

        self.api_endpoint = os.getenv("ARGO_API_ENDPOINT")
        if not self.api_endpoint:
            raise ValueError("ARGO_API_ENDPOINT env var is not set")

        self.user = os.getenv("ARGO_USER")
        if not self.user:
            raise ValueError("ARGO_USER env var is not set")

        self.model = model

    def chat(self, chat_template):

        # Combine all role/content pairs into a single text block
        prompt_text = "\n\n".join(
            f"{item['role'].capitalize()}: {item['content'].strip()}"
            for item in chat_template
        )

        # Data to be sent as a POST in JSON format
        data = {
            "user": self.user,
            "model": self.model,
            "system": "You are a large language model with the name Argo.",
            "prompt": [prompt_text],
            "stop": [],
            "temperature": 0.1,
            "top_p": 0.9,
        }

        response = requests.post(
            self.api_endpoint,
            data=json.dumps(data),
            headers={"Content-Type": "application/json"},
        )

        return response.json()["response"]


class PerplexityModel:
    def __init__(self):
        perplexity = importlib.import_module("perplexity")
        self.pipeline = perplexity.Perplexity()

    def chat(self, chat_template):
        pass


class KimiModel:
    """
    Client for a locally hosted OpenAI-compatible Chat Completions API.

    Expects the API key in env var: KIMI_API_KEY
    Expects the API endpoint in env var: KIMI_API_ENDPOINT

    Default model:
      moonshotai/Kimi-K2-Instruct
    """

    def __init__(
        self,
        model: str = "moonshotai/Kimi-K2-Instruct",
        outputs: int = 1,
        max_tokens: int = 4096,
        timeout: int = 120,
    ):
        self.api_key = os.getenv("KIMI_API_KEY")
        if not self.api_key:
            raise ValueError("KIMI_API_KEY env var is not set")

        self.endpoint = os.getenv("KIMI_API_ENDPOINT")
        if not self.endpoint:
            raise ValueError("KIMI_API_ENDPOINT env var is not set")

        self.model = model
        self.outputs = outputs
        self.max_tokens = max_tokens
        self.timeout = timeout

        self._session = requests.Session()
        self._headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
        }

    def chat(self, chat_template: List[Dict[str, str]]) -> str:
        """
        Send messages to the chat completion endpoint.

        Parameters
        ----------
        chat_template : list[dict]
            OpenAI-style messages, e.g.:
            [
              {"role": "system", "content": "You are helpful."},
              {"role": "user", "content": "Hello!"}
            ]

        Returns
        -------
        str
            The assistant's reply (first choice).
        """
        payload = {
            "model": self.model,
            "messages": chat_template,
            "max_tokens": self.max_tokens,
            "n": self.outputs,
        }

        resp = self._session.post(
            self.endpoint, headers=self._headers, json=payload, timeout=self.timeout
        )
        try:
            resp.raise_for_status()
        except requests.HTTPError as e:
            raise RuntimeError(f"HTTP {resp.status_code}: {resp.text}") from e

        data = resp.json()

        try:
            return data["choices"][0]["message"]["content"]
        except (KeyError, IndexError) as e:
            raise RuntimeError(f"Unexpected response format: {data}") from e


class QwenModel:
    """
    Client for a locally hosted OpenAI-compatible Chat Completions API.

    Expects the API key in env var: KIMI_API_KEY
    Default endpoint:
      http://llm.ai.r-ccs.riken.jp:11434/kimi/v1/chat/completions
    Default model:
      moonshotai/Kimi-K2-Instruct
    """

    def __init__(
        self,
        model: str = "qwen3-coder:30b",
        outputs: int = 1,
        max_tokens: int = 4096,
        timeout: int = 120,
    ):
        self.api_key = os.getenv("KIMI_API_KEY")
        if not self.api_key:
            raise ValueError("KIMI_API_KEY env var is not set")

        self.endpoint = os.getenv("KIMI_API_ENDPOINT")
        if not self.endpoint:
            raise ValueError("KIMI_API_ENDPOINT env var is not set")

        self.model = model
        self.outputs = outputs
        self.max_tokens = max_tokens
        self.timeout = timeout

        self._session = requests.Session()
        self._headers = {
            "Content-Type": "application/json",
        }

    def chat(self, chat_template: List[Dict[str, str]]) -> str:
        """
        Send messages to the chat completion endpoint.

        Parameters
        ----------
        chat_template : list[dict]
            OpenAI-style messages, e.g.:
            [
              {"role": "system", "content": "You are helpful."},
              {"role": "user", "content": "Hello!"}
            ]

        Returns
        -------
        str
            The assistant's reply (first choice).
        """
        payload = {
            "model": self.model,
            "messages": chat_template,
            "max_tokens": self.max_tokens,
            "n": self.outputs,
        }

        resp = self._session.post(
            self.endpoint, headers=self._headers, json=payload, timeout=self.timeout
        )
        try:
            resp.raise_for_status()
        except requests.HTTPError as e:
            raise RuntimeError(f"HTTP {resp.status_code}: {resp.text}") from e

        data = resp.json()

        try:
            return data["choices"][0]["message"]["content"]
        except (KeyError, IndexError) as e:
            raise RuntimeError(f"Unexpected response format: {data}") from e


class TFModel:
    def __init__(self, checkpoint_dir):
        transformers = importlib.import_module("transformers")
        torch = importlib.import_module("torch")

        self.tokenizer = transformers.AutoTokenizer.from_pretrained(checkpoint_dir)
        self.pipeline = transformers.pipeline(
            "text-generation",
            model=checkpoint_dir,
            # torch_dtype=torch.float16,
            device=-1,
        )

        self.max_new_tokens = 4096
        self.batch_size = 8
        self.max_length = None

    def chat(self, chat_template):

        results = self.pipeline(
            chat_template,
            max_new_tokens=self.max_new_tokens,
            max_length=self.max_length,
            batch_size=self.batch_size,
            # temperature=temperature,
            # top_p=top_p,
            # do_sample=True,
            eos_token_id=self.tokenizer.eos_token_id,
            pad_token_id=50256,
        )

        return results[0]["generated_text"][-1]["content"]


def _set_neural_model(model):
    """
    Set neural model based on options
    """
    if os.path.exists(model):
        neural_model = TFModel(model)

    elif model.lower() == "openai":
        neural_model = OpenAIModel()

    elif model.lower().startswith("argo-"):
        neural_model = ArgoModel(model.lower().strip("argo")[1:])

    elif model.lower() == "kimi":
        neural_model = KimiModel()

    elif model.lower() == "qwen":
        neural_model = QwenModel()

    else:
        raise ValueError(f"{model} not available")

    return neural_model


def prompt_translate(mapping, seed_prompt, model=None, save_prompts=False):
    """
    perform translation using prompts and the supplied model.
    """
    neural_model = None

    if model:
        print("Starting neural conversion process")
        neural_model = _set_neural_model(model)

    if save_prompts:
        print("Saving custom prompts per file")

    chat_template = toml.load(seed_prompt)["chat"]

    with alive_bar(len(mapping[0]), bar="blocks") as bar:

        for fsource, csource, finterface, cdraft, promptfile, cheader in zip(
            mapping[0], mapping[1], mapping[2], mapping[3], mapping[4], mapping[5]
        ):

            bar.text(fsource)
            bar()

            if not os.path.isfile(csource) or save_prompts:
                cached_prompt = chat_template[-1]["content"]

                with open(fsource, "r") as sfile:
                    is_comment = False
                    source_code = []

                    for line in sfile.readlines():
                        is_comment = False

                        if line.strip().lower().startswith(("c", "!!", "!")) and (
                            not line.strip().lower().startswith(("complex"))
                        ):
                            is_comment = True

                        if not is_comment:
                            source_code.append(line)

                    if source_code:
                        chat_template[-1]["content"] += (
                            "\n" + "<source>\n" + "".join(source_code) + "</source>"
                        )

                if os.path.isfile(cdraft):

                    draft_code = []
                    with open(cdraft) as dfile:
                        for line in dfile.readlines():
                            draft_code.append(line)

                        if draft_code:
                            chat_template[-1]["content"] += (
                                "\n\n" + "<draft>\n" + "".join(draft_code) + "</draft>"
                            )

                if save_prompts:
                    with open(promptfile, "w") as pdest:
                        # for instance in chat_template:
                        #    pdest.write("[[chat]]\n")
                        #    pdest.write(f'role = "{instance["role"]}"\n')
                        #    pdest.write(f'content = """\n{instance["content"]}"""\n\n')
                        json.dump(chat_template, pdest, indent=4)
                    print(f"Generated prompt file for LLM consumption {promptfile}")

                if neural_model:
                    result = neural_model.chat(chat_template)

                    with open(csource, "w") as cdest, open(
                        finterface, "w"
                    ) as fdest, open(cheader, "w") as chead:

                        cheader = re.search(
                            r"<cheader>(.*?)</cheader>", result, re.DOTALL
                        )
                        csource = re.search(
                            r"<csource>(.*?)</csource>", result, re.DOTALL
                        )
                        fsource = re.search(
                            r"<fsource>(.*?)</fsource>", result, re.DOTALL
                        )

                        if csource:
                            cdest.write(csource.group(1))
                        else:
                            cdest.write(result)

                        if cheader:
                            chead.write(cheader.group(1))
                        else:
                            chead.write(result)

                        if fsource:
                            fdest.write(fsource.group(1))

                chat_template[-1]["content"] = cached_prompt

            else:
                continue


def prompt_inspect(
    filelist, query_prompt, file_index={}, model=None, save_prompts=False
):
    """
    Perform inspect on a list of files using a query prompt
    """
    neural_model = None

    if model:
        print("Performing neural inspection")
        neural_model = _set_neural_model(model)

    if save_prompts:
        print("Saving prompts to scribe.json")

    chat_template = [{"role": "system", "content": ""}]

    chat_template[-1]["content"] += (
        "You are a coding assistant.\n"
        + "The user will give you source code from a set of files that\n"
        + "belong to a scientific computing codebase. Understand the\n"
        + "source code and answer a query that follows.\n"
        + "Source code for each file will be separated using\n"
        + "elements <filename> ... </filename>. Additional\n"
        + "information related to the project structure may also be\n"
        + "provided within <index> ... </index>. This information will\n"
        + "contain an index of subroutines, functions, and modules contained\n"
        + "in each file. Note that you will find subroutines and functions\n"
        + "repeat along nodes in the directory tree. This maybe due to a directory-based\n"
        + "inheritance design implemented by the project. If the index element is not\n"
        + "present, then you may ignore it. The query prompt will be provided at the end\n"
        + "using elements <query> ... </query>.\n\n"
    )

    chat_template.append({"role": "user", "content": ""})

    filtered_file_index = {}
    for fsource in filelist:

        if file_index:
            filtered_file_index.update(lib.filter_file_indexes(fsource, file_index))

        with open(fsource, "r") as sfile:
            source_code = []

            for line in sfile.readlines():
                source_code.append(line)

        if source_code:
            chat_template[-1]["content"] += (
                "\n" + f"<{fsource}>\n" + "".join(source_code) + f"</{fsource}>\n"
            )

    if filtered_file_index:
        chat_template[-1]["content"] += "<index>\n"
        for construct, file_path in filtered_file_index.items():
            chat_template[-1]["content"] += f"{construct}: {file_path}\n"
        chat_template[-1]["content"] += "</index>\n\n"

    chat_template[-1]["content"] += "\n" + f"<query>\n" + query_prompt + f"\n</query>\n"

    if save_prompts:
        with open("scribe.json", "w") as pdest:
            json.dump(chat_template, pdest, indent=4)

    if neural_model:
        result = neural_model.chat(chat_template)
        print(result)


def prompt_generate(seed_prompt, model=None, save_prompts=False, reference_existing=[]):
    """
    Perform code understanding
    """
    neural_model = None

    if model:
        print("Performing neural generation")
        neural_model = _set_neural_model(model)

    if save_prompts:
        print("Saving prompts to scribe.json")

    system_template = [{"role": "system", "content": ""}]
    system_template[-1]["content"] += (
        "You are a code generation and editing assistant.\n"
        + "When the user asks for code that spans multiple files,\n"
        + "output each file enclosed within\n"
        + "XML-style tags using the format:\n"
        + "\n"
        + "<filename1>\n"
        + "... file contents ...\n"
        + "</filename1>\n"
        + "\n"
        + "<filename2>\n"
        + "... file contents ...\n"
        + "</filename2>\n"
        + "\n"
        + "Do not add any explanations or commentary outside of these tags.\n"
        + "Note that some of these files may be requested to be treated as read-only.\n"
        + "Do not edit or generate files that are requested as ready only."
    )

    chat_template = system_template + toml.load(seed_prompt)["chat"]

    if reference_existing:
        chat_template[-1]["content"] += (
            "Use the content of following files as a reference to \n"
            + "update the files above. Do not edit the files below, treat them as read-only\n\n"
        )

        for filename in reference_existing:
            with open(filename, "r") as sfile:
                source_code = []

                for line in sfile.readlines():
                    source_code.append(line)

            if source_code:
                chat_template[-1]["content"] += (
                    "\n" + f"<{filename}>\n" + "".join(source_code) + f"</{filename}>\n"
                )

    if save_prompts:
        with open("scribe.json", "w") as pdest:
            json.dump(chat_template, pdest, indent=4)

    if neural_model:
        result = neural_model.chat(chat_template)

        pattern = re.compile(r"<([^>]+)>\s*(.*?)\s*</\1>", re.DOTALL)

        for match in pattern.finditer(result):
            filename, content = match.groups()
            # Ensure directory exists if filename has subpaths
            os.makedirs(os.path.dirname(filename) or ".", exist_ok=True)
            # Write to file
            with open(filename, "w") as f:
                f.write(content.strip() + "\n")
            print(f"Wrote {filename}")


def prompt_update(filelist, seed_prompt, model=None, reference_existing=[]):
    """
    Perform code understanding
    """
    neural_model = None

    print("Performing neural update")
    neural_model = _set_neural_model(model)

    system_template = [{"role": "system", "content": ""}]
    system_template[-1]["content"] += (
        "You are a code generation and editing assistant.\n"
        + "When the user asks for code that spans multiple files,\n"
        + "output each file enclosed within\n"
        + "XML-style tags using the format:\n"
        + "\n"
        + "<filename1>\n"
        + "... file contents ...\n"
        + "</filename1>\n"
        + "\n"
        + "<filename2>\n"
        + "... file contents ...\n"
        + "</filename2>\n"
        + "\n"
        + "Do not add any explanations or commentary outside of these tags.\n"
        + "Note that some of these files may be requested to be treated as read-only or may note be appended.\n"
        + "Do not edit files if they are not appended or requested as read-only."
    )

    chat_template = system_template + toml.load(seed_prompt)["chat"]

    if set(filelist) & set(reference_existing):
        raise ValueError("Reference and target files should be mutually exclusive")

    if filelist:
        chat_template[-1]["content"] += (
            "Update the content of following files based on\n"
            + "the instructions. Enclose output of each file in their\n"
            + "respective XML elements. Only update the following files.\n\n"
        )

        for filename in filelist:
            with open(filename, "r") as sfile:
                source_code = []

                for line in sfile.readlines():
                    source_code.append(line)

            if source_code:
                chat_template[-1]["content"] += (
                    "\n" + f"<{filename}>\n" + "".join(source_code) + f"</{filename}>\n"
                )

    if reference_existing:
        chat_template[-1]["content"] += (
            "Use the content of following files as a reference to \n"
            + "update the files above. Do not edit the files below, treat them as read-only\n\n"
        )

        for filename in reference_existing:
            with open(filename, "r") as sfile:
                source_code = []

                for line in sfile.readlines():
                    source_code.append(line)

            if source_code:
                chat_template[-1]["content"] += (
                    "\n" + f"<{filename}>\n" + "".join(source_code) + f"</{filename}>\n"
                )

    if neural_model:
        result = neural_model.chat(chat_template)

        pattern = re.compile(r"<([^>]+)>\s*(.*?)\s*</\1>", re.DOTALL)

        for match in pattern.finditer(result):
            filename, content = match.groups()
            # Ensure directory exists if filename has subpaths
            os.makedirs(os.path.dirname(filename) or ".", exist_ok=True)
            # Write to file
            with open(filename, "w") as f:
                f.write(content.strip() + "\n")
            print(f"Wrote {filename}")
